## 2026-09-01

- embedded systems collide with the real world

- Analog design for Digital


- square with x is the symbol for the pin

- Receive side of a chip is basically a capacitor
- Programmable pull-up and pull-down switches

$$ \frac{V_\text{dd} - V_\text{on}}{R_s} + R_d $$

- Double-check pin current limit!!! (probably around 8mA)

- Make sure to learn idiomatic system verilog

## 2026-09-03
- Career Capital: this is the foundation on which we can stand to be able to use AI effectively
    - As HMC students we have often chosen the hard way, which makes us good
    - There is a value to good old-fashioned expertise

- Don't design asynchronous systems if you want to sleep
    - huge [pita](https://xkcd.com/1671/) to debug

- $V_{IH}$ is lowest input voltage logical 1
- $V_{IL}$ is highest input voltage logical 0
- $V_{OH}$ is lowest output voltage logical 1
- $V_{OL}$ is highest output voltage logical 0
- Source and sink limits per pin vary (are not symmetric)
- `always_ff` makes errors (according to standard) when you don't imply a ff (which is not the case for `always`)

## 2026-09-08
- Sorry about Radiant licensing
- Encourage us to not pressure us to be too detailed if we don't want to
    - Don't write too much for the lab report
    - Prose is more for others, not for the checkoffs
- Finish hardware by Thursday night in order to get extra hardware if necessary
    - basically, ensure that everything is working
- Try writing the block diagram prior to writing the systemverilog
- Note to self: start building with synchronous reset if possible as it is cheaper
- Don't do pre-assignment because it can violate idioms. Just use `else`
- According to Prof. Spencer `casex` and `casez` will just make you unhappy: use `case`
- always good practice to add `default` to `case` statement even if you cover every case, just in
  case something gets removed down the line or similar
- avoid race conditions when simulating (as there is no guarantee on the different simulators)

## 2026-09-10
- Synchronous Design (we love it!)
- When do we use FSM's versus not
    - Sometimes when you are not thinking, the result will not be optimized
- Good practice to not change signals at exactly the clock edge
- Every flop should be triggered on the same clock
    - this includes things that must not change every clock cycle
    - fix this with an `enable` that is triggered at a special time
    - so in this case, do weird shit with the scan frequency thing
        - check count to be a special number, which triggers the enable for the flop
- Don't just pick a bit (from a counter) and map it as an input for the flop (as a clk signal)
- Synchronizers
    - if things go metastable (it eventually resolves, but could technically take infinitely long)
    - never want to take async input and feed it into sync system (so lab 2 for example)
        - might make a decision to give it async input as it will be passed through to debounce


Photon detector verilog
```systemverilog
module photon_detector(input logic clk, reset, photon,
                       output logic photon_detected)

    typedef enum logic [1:0] {no_photon, pulse, yes_photon} fsm_states;
    fsm_states state;

    // next state logic
    always_ff @(posedge clk) begin
        if (reset) state <= no_photon;
        else
            case (state)
                no_photon: if (photon=1)  state <= pulse,
                yes_photon: if (photon=0) state <= no_photon,
                pulse:                    state <= yes_photon,
                default:                  state <= state,
            endcase
    end

    always_comb
        if (state == pulse)
            photon_detected = 1'b1;
        else
            photon_detected = 1'b0;
    end
```

- note that the edge detector can be done much more easily with less logic
- also note that this code is also possible, but it might be nice to seperate the next state logic
  flip flop logic and the combinational logic that determines what the next state will be
